/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppHome {
    'socketConnection': any;
  }
  interface AppHomeAttributes extends StencilHTMLAttributes {
    'socketConnection'?: any;
  }

  interface AppFlower {
    'calculateFlowerState': () => void;
    /**
    * Device reading object that is passed from the app-home component to this flower component. Contains all the flower data (deviceId, etc).
    */
    'flower': any;
  }
  interface AppFlowerAttributes extends StencilHTMLAttributes {
    /**
    * Device reading object that is passed from the app-home component to this flower component. Contains all the flower data (deviceId, etc).
    */
    'flower'?: any;
  }

  interface AppMeasurements {
    'fertility': number;
    'lux': number;
    'moisture': number;
    'temperature': number;
  }
  interface AppMeasurementsAttributes extends StencilHTMLAttributes {
    'fertility'?: number;
    'lux'?: number;
    'moisture'?: number;
    'temperature'?: number;
  }

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppFlower': Components.AppFlower;
    'AppMeasurements': Components.AppMeasurements;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-flower': Components.AppFlowerAttributes;
    'app-measurements': Components.AppMeasurementsAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppFlowerElement extends Components.AppFlower, HTMLStencilElement {}
  var HTMLAppFlowerElement: {
    prototype: HTMLAppFlowerElement;
    new (): HTMLAppFlowerElement;
  };

  interface HTMLAppMeasurementsElement extends Components.AppMeasurements, HTMLStencilElement {}
  var HTMLAppMeasurementsElement: {
    prototype: HTMLAppMeasurementsElement;
    new (): HTMLAppMeasurementsElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-flower': HTMLAppFlowerElement
    'app-measurements': HTMLAppMeasurementsElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-flower': HTMLAppFlowerElement;
    'app-measurements': HTMLAppMeasurementsElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
